### ISSUE TITLE
Bug: Recompiling while UnityConvertersConfigEditor scriptable object asset selected and shown in inspector throws exception

### ISSUE THREAD

**Issue by EpsilonD3lta** [applejag/Newtonsoft.Json-for-Unity.Converters#82]
## Expected behavior
UnityConvertersConfigEditor scriptable object asset throws no exceptions

## Actual behavior
UnityConvertersConfigEditor scriptable object asset throws error after recompiling scripts in Unity 2022.3.0 when selected and shown in inspector:

`NullReferenceException: Object reference not set to an instance of an object
UnityEditor.EditorStyles.get_label () (at <4911eca47f294e18a7b3306f02701303>:0)
Newtonsoft.Json.UnityConverters.Editor.UnityConvertersConfigEditor.OnEnable () (at ./Library/PackageCache/jillejr.newtonsoft.json-for-unity.converters@1.6.0/Editor/UnityConvertersConfigEditor.cs:71)`

It's this line of code:
`_headerStyle = new GUIStyle { fontSize = 20, wordWrap = true, normal = EditorStyles.label.normal };`
EditorStyles.label does not exist at the moment when OnEnable is running.  Either don't use it or set it somewhere where it exists like OnInspectorGUI.
Next line of code has the same problem

## Steps to reproduce

- New project in Unity 2022.3.0
- Import `jillejr.newtonsoft.json-for-unity` via UPM
- Import `jillejr.newtonsoft.json-for-unity.converters` via UPM
- Create and select UnityConvertersConfigEditor scriptable object asset and Recompile scripts

## Details
- Windows 10
- Android build target
- Package version 1.6.0
- Unity 2022.3.0f1

**Comment by applejag** [comment]
Hello, @EpsilonD3lta, great find!

Would you like to create a PR to fix this? I won't be behind my computer until next year

**Comment by EpsilonD3lta** [comment]
Sure, I will try to use this approach of lazy init. Is that ok? 
https://discussions.unity.com/t/editorstyles-null-reference/238470

**Comment by applejag** [comment]
Yea sure! Could maybe make use of [`System.Lazy<T>`(https://learn.microsoft.com/en-us/dotnet/api/system.lazy-1?view=net-8.0), or just moving the `_headerStyle = new GUIStyle` line to inside `OnInspectorGUI`. Up to you :)

**Comment by EpsilonD3lta** [comment]
I like the static constructor approach from the link I provided. I use it myself often, does the same job with less words for such simple case. You can certainly change it to System.Lazy<T> if you find it better.

**Comment by applejag** [comment]
Thank you so much for your contribution! I will release a v1.6.1 shortly
